<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="jieba.NET" GeneratePathProperty="true" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Rougamo.Fody" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="BERTTokenizers" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="Tokenizers.HuggingFace" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(Pkgjieba_NET)\Resources\**\*.*">
      <Link>Resources\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
