<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Release 模式下不生成调试文件 (.pdb) -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="McpHelper.Core" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReferenceRAG.Core\ReferenceRAG.Core.csproj" />
    <ProjectReference Include="..\ReferenceRAG.Storage\ReferenceRAG.Storage.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <SpaRoot>..\..\dashboard-vue\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
  </PropertyGroup>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish" Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' != 'true'">
    <Message Importance="high" Text="Restoring dependencies using 'npm'..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Message Importance="high" Text="Building the Vue frontend..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>

    <ItemGroup>
      <ScriptFiles Include="scripts\**" />
      <ResolvedFileToPublish Include="@(ScriptFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>scripts\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

</Project>